### ISSUE TITLE
"Zits" On External Wall Of Curved Objects Or Curved Sections Of Objects

### ISSUE THREAD

**Issue by jlwainwright** [Desuuuu/DGUS-reloaded-config#2]
Printer: Creality CR10s-Pro V2

Firmware: https://github.com/Desuuuu/Marlin

System Board: Creality 3D v2.4

Issue: Stuttering Print Motion Result In "Zits" On External Wall Of Curved Objects Or Curved Sections Of Objects

<blockquote class="imgur-embed-pub" lang="en" data-id="a/YbOKk0J" data-context="false"><a href="//imgur.com/a/YbOKk0J">Refer To Image</a></blockquote>

Object On Left - > DGUS-reloaded-config
Object On Right - > Creality Stock Firmware

**Comment by Desuuuu** [comment]
The problem you're experiencing is related to the throughput of commands achievable by the firmware. Curves generate a lot of commands hence the stuttering.

There isn't a direct comparison with Creality's firmware since it's based on an old version of Marlin, while this is based on Marlin 2.0, which is heavier.

There are a two ways to reduce this behaviour: increase resolution (minimum segment length) and decrease speed. Playing around with acceleration might also help but I'm not sure.

While there might be some configuration tweaks to be done here to reduce this behaviour, I don't think this issue is specific to this firmware.

**Comment by jlwainwright** [comment]
Hi @Desuuuu 

It seems that the TM3D firmware is set to cope very well with this.

I do not have the source code but I would guess that they have tweaked their BLOCK_BUFFER_SIZE, MAX_CMD_SIZE BUFSIZE and TX_BUFFER_SIZE? It would seem that their FW is also based on Marlin2.0?

I have tested using the same GCODE file between the firmwares.

**Comment by Desuuuu** [comment]
The source code for TinyMachines' firmware is available [here](https://github.com/InsanityAutomation/Marlin/tree/CrealityDwin_2.0) (the CrealityDwin_2.0 branch has the version built on Marlin 2.x).

They appear to use a lower `BLOCK_BUFFER_SIZE` for the CR-10S Pro, but I don't think lowering the buffer would improve anything here. The other values you mentionned are serial-related so they should not impact printing from the micro SD (also they're similar).

Do you happen to have the filename for the version you installed? They have a lot of variations and also some older versions built on Marlin 1.x.

Could you also provide your G-code file? I'd like to see if the acceleration parameters are included in it or if it uses the firmware's default values.

**Comment by jlwainwright** [comment]
Hi @Desuuuu 

Thanks.

I have been flashing with the pre-compiled version that is here: [https://github.com/InsanityAutomation/Marlin/blob/CrealityDwin_2.0/Hex%20Files/10SProV2_BIL_DW6.2.hex.gz](url)


GCODE: [https://drive.google.com/file/d/1hnNUDHh9G9C7D8ua6UYV2huVxB67lBiX/view?usp=sharing](url)

**Comment by Desuuuu** [comment]
Thanks, that should be all I need to get to the bottom of this.

Your Google Drive link requires an authorization to access the file. Could you make it public please?

**Comment by jlwainwright** [comment]
> Your Google Drive link requires an authorization to access the file. Could you make it public please?

Please try again now.

**Comment by Desuuuu** [comment]
Got it, thanks!

I'll let you know what I find.

**Comment by Desuuuu** [comment]
There aren't that many configuration differences between the two firmwares. The main differences are (the acceleration values most likely don't matter since your G-code file sets its own values):

```diff
- #define DEFAULT_MAX_ACCELERATION      { 1000, 1000, 100, 2000 }
+ #define DEFAULT_MAX_ACCELERATION      { 750, 750, 100, 60 }

- #define DEFAULT_TRAVEL_ACCELERATION   2000    // X, Y, Z acceleration for travel (non printing) moves
+ #define DEFAULT_TRAVEL_ACCELERATION    300    // X, Y, Z acceleration for travel (non printing) moves

- #define JUNCTION_DEVIATION_MM 0.05 // (mm) Distance from real junction edge
+ #define JUNCTION_DEVIATION_MM 0.06 // (mm) Distance from real junction edge

- #define BLOCK_BUFFER_SIZE 16 // SD,LCD,Buttons take more memory, block buffer needs to be smaller
+ #define BLOCK_BUFFER_SIZE 8 // SD,LCD,Buttons take more memory, block buffer needs to be smaller
```

I don't expect this to make much of a difference. There's also [this issue](https://github.com/InsanityAutomation/Marlin/issues/134) that has been reported with TM's 2.x-based firmware that appears to be the same as yours.

In the comments on the issue, someone suggests that this has something to do with Marlin's junction deviation.

Starting with version 2.0.5.4, the default configurations use classic jerk. Let me know if that helped with the issue.
